name: 'Move Card in Zenhub'
description: 'This action integrates Zenhub api. To automatically move card between pipelines'
inputs:
  zh-token:
    description: 'token for zenhub api'
    required: true
  zh-workspace-id:
    description: 'workspace id in zenhub'
    required: true
  zh-target-pipeline-id:
    description: 'target pipeline id in zenhub'
    required: false
  zh-target-pipeline-name:
    description: 'target pipeline name in zenhub'
    required: false
  github-token:
    description: 'token for github api'
    required: true
  pr-url:
    description: 'pr url to parse issues'
    required: true
  zh-repository-id:
    description: 'zenhub repository id'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: activity
  color: purple
